apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  labels:
    app: capstone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
        - name: capstone-app
          image: capstone-app:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
