Description: >
  Yemitan Rotimi / Cloud devops nanodegree capstone project
  Setup a bastion host

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow http and ssh on bastion instance"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06d51e91cea0dac8d
      InstanceType: t2.medium
      KeyName: "Bastion"
      SecurityGroupIds:
        - Ref: BastionSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SUBNETS
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          apt-get update -y
          apt install docker.io -y
          docker run -d -p 80:80 rhotimee/capstone-app
