---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: 'Amazon EKS Service Role'
  
  
  Resources:
  
    eksServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - eks.amazonaws.com
            Action:
            - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
          - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  
  Outputs:
  
    RoleArn:
      Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
      Value: !GetAtt eksServiceRole.Arn
      Export:
        Name: !Sub "${AWS::StackName}-RoleArn"