Description: >
  Yemitan Rotimi / Cloud devops nanodegree capstone project
  Setup Jenkins

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow http and ssh on bastion instance"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06d51e91cea0dac8d
      InstanceType: t2.medium
      KeyName: "Bastion"
      SecurityGroupIds:
        - Ref: JenkinsSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SUBNETS
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          apt install -y openjdk-8-jre
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          apt update
          sudo apt install jenkins -y
          sudo systemctl start jenkins
          sudo ufw allow 8080
